[package]
name = "recli"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
portable-pty = "0.8"
crossterm = "0.27"
tokio = { version = "1.0", features = ["full"] }
